# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170517_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, verbose_name='\u8bc4\u8bba\u8005\u6635\u79f0')),
                ('mail', models.EmailField(max_length=255, verbose_name='\u8bc4\u8bba\u8005\u90ae\u7bb1')),
                ('content', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u8bc4\u8bba\u53d1\u8868\u65f6\u95f4')),
                ('pid', models.IntegerField(default=0, verbose_name='\u7236\u7ea7id')),
                ('module_id', models.IntegerField(default=0, verbose_name='\u6a21\u5757\u4e0b\u5185\u5bb9\u7684id')),
                ('module', models.CharField(max_length=30, verbose_name='\u6240\u5c5e\u6a21\u5757')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='img_is_centent_show',
            field=models.SmallIntegerField(choices=[(1, '\u5c55\u793a'), (0, '\u4e0d\u5c55\u793a')], default=0, verbose_name='\u9996\u9875\u56fe\u7247\u662f\u5426\u5728\u6587\u7ae0\u9876\u7aef\u5c55\u793a'),
        ),
    ]
